#h2
server:
  port: 8183
  servlet:
    context-path: /tech-bazzar-core
spring:
  servlet:
    multipart:
      max-file-size: 5MB

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:tech_bazzar_core;MODE=PostgreSQL
    username: sa
    password:
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: false
  flyway:
    baselineOnMigrate: true
    url: jdbc:h2:mem:tech_bazzar_core;MODE=PostgreSQL
    user: sa
    password:
    validateOnMigrate: false

    jpa:
      show-sql: true
      database-platform: org.hibernate.dialect.PostgreSQL94Dialect
      hibernate:
        ddl-auto: update

integrations:
  auth-service:
    url: http://localhost:8181/tech-bazzar-auth/
    read-timeout: 10000
    write-timeout: 5000
    connect-timeout: 5000

  cart-service:
    url: http://localhost:8182/tech-bazzar-cart/
    read-timeout: 10000
    write-timeout: 5000
    connect-timeout: 5000

  organization-service:
    url: http://localhost:8185/tech-bazzar-organization/
    read-timeout: 10000
    write-timeout: 5000
    connect-timeout: 5000

  picture-service:
    url: http://localhost:8555/tech-bazzar-picture/
    read-timeout: 10000
    write-timeout: 5000
    connect-timeout: 5000