server:
  port: 8186
  servlet:
    context-path: /tech-bazzar-keycloak

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${issuer_uri}
          jwk-set-uri: ${jwk_set_uri}

client:
  url: http://localhost:3000
