server:
  port: 8184
  servlet:
    context-path: /tech-bazzar-notification

spring:
  flyway:
    baselineOnMigrate: true
    url: jdbc:postgresql://postgres-notification-service:5434/notification_db
    user: postgres
    password: admin
    validateOnMigrate: false

  datasource:
    url: jdbc:postgresql://postgres-notification-service:5434/notification_db
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: admin

  jpa:
    showSql: true
    databasePlatform: org.hibernate.dialect.PostgreSQL94Dialect
    hibernate:
      ddlAuto: update

  mail:
    protocol: smtps
    host: smtp.mail.ru
    port: 465
    username: nik.noreply.b@mail.ru
    password: pWKMSE90ncXznJQvjmA2

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-service:8761/eureka