server:
  port: 8185
  servlet:
    context-path: /tech-bazzar-organization

spring:
  datasource:
    url: jdbc:postgresql://postgres-organization-service:5435/organization_db
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: admin

  flyway:
    baselineOnMigrate: true
    url: jdbc:postgresql://postgres-organization-service:5435/organization_db
    user: postgres
    password: admin
    validateOnMigrate: false

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    hibernate:
      ddl-auto: update

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-service:8761/eureka

springdoc:
  swagger-ui:
    supported-submit-methods: "get"
