#h2
server:
  port: 8555
  servlet:
    context-path: /tech-bazzar-picture

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:tech_bazzar_picture;MODE=PostgreSQL
    username: sa
    password:

  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        ddl-auto: update
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: false

  flyway:
    baselineOnMigrate: true
    url: jdbc:h2:mem:tech_bazzar_picture;MODE=PostgreSQL
    user: sa
    password:
    validateOnMigrate: false