server:
  port: 5555

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - DELETE
              - PUT
            allowedHeaders: "*"


      routes:
        - id: core-service
          uri: http://localhost:8183
          predicates:
            - Path=/core/**
          filters:
            - StripPrefix=1
            - PrefixPath=/tech-bazzar-core
            - TokenAuthenticationFilter

        - id: cart-service
          uri: http://localhost:8182
          predicates:
            - Path=/cart/**
          filters:
            - StripPrefix=1
            - PrefixPath=/tech-bazzar-cart
            - TokenAuthenticationFilter

        - id: notification-service
          uri: http://localhost:8184
          predicates:
            - Path=/notification/**
          filters:
            - StripPrefix=1
            - PrefixPath=/tech-bazzar-notification
            - TokenAuthenticationFilter

        - id: organization-service
          uri: http://localhost:8185
          predicates:
            - Path=/organization/**
          filters:
            - StripPrefix=1
            - PrefixPath=/tech-bazzar-organization
            - TokenAuthenticationFilter

        - id: user-service
          uri: http://localhost:8181
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
            - PrefixPath=/tech-bazzar-auth
            - TokenAuthenticationFilter

  servlet:
    multipart:
      max-file-size: 5MB

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${issuer_uri}
          jwk-set-uri: ${jwk_set_uri}